version: '3.8'

services:
  app:
    build: .
    ports:
      - "2456:2456"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: