version: '3.9'

services:
  app:
    build: .
    container_name: willhaben-app
    ports:
      - "2456:2456"
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 2456
      ADMIN_PORT: 3001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      SQLITE_PATH: /data/listener.db
      ENABLE_METRICS: 'true'
      LOG_LEVEL: info
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - app-data:/data
      - app-logs:/logs
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:2456/listener/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:alpine
    container_name: willhaben-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  app-data:
  app-logs:
  redis-data:


