services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2456:2456"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HOST=0.0.0.0
      - PORT=2456
    volumes:
      - ./public:/usr/src/app/public:ro
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: